name: chat_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # All packages are now correctly listed together
  cupertino_icons: ^1.0.8
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  google_generative_ai: ^0.4.0
  firebase_storage: ^12.1.0
  image_picker: ^1.1.2
  lottie: ^3.1.2
  intl: ^0.19.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/chat.png
    - assets/images/avatar.png
    - assets/animations/social.json
    - assets/animations/empty_chat.json