// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj31q8bDhfvbSUsd7WM1LR7HF8H37kBUU',
    appId: '1:195801809453:android:3f3bc533b68662ec0e6ea4',
    messagingSenderId: '195801809453',
    projectId: 'flutter-chat-app-d2964',
    storageBucket: 'flutter-chat-app-d2964.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9oYZ6FR-WjORVUyZbJadb9IO4VwZf50U',
    appId: '1:195801809453:web:42d5c61ea1a9abc20e6ea4',
    messagingSenderId: '195801809453',
    projectId: 'flutter-chat-app-d2964',
    authDomain: 'flutter-chat-app-d2964.firebaseapp.com',
    storageBucket: 'flutter-chat-app-d2964.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqxNx4WF-CAoewPp01PGNbl4fz1HKBiO4',
    appId: '1:195801809453:ios:1e1810bddeb937010e6ea4',
    messagingSenderId: '195801809453',
    projectId: 'flutter-chat-app-d2964',
    storageBucket: 'flutter-chat-app-d2964.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqxNx4WF-CAoewPp01PGNbl4fz1HKBiO4',
    appId: '1:195801809453:ios:1e1810bddeb937010e6ea4',
    messagingSenderId: '195801809453',
    projectId: 'flutter-chat-app-d2964',
    storageBucket: 'flutter-chat-app-d2964.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9oYZ6FR-WjORVUyZbJadb9IO4VwZf50U',
    appId: '1:195801809453:web:b9ad208dd95a5f480e6ea4',
    messagingSenderId: '195801809453',
    projectId: 'flutter-chat-app-d2964',
    authDomain: 'flutter-chat-app-d2964.firebaseapp.com',
    storageBucket: 'flutter-chat-app-d2964.firebasestorage.app',
  );

}